GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/info

###

GET http://localhost:3001/api/persons/62174565e05ab3e31d99484a

###

DELETE http://localhost:3001/api/persons/6219d8b2f96903ea3cdd1a98

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "William",
    "number": "12345678"
}

###

PUT http://localhost:3001/api/persons/6219f3c53eeea8d93cc19b46
Content-Type: application/json

{
    "number": "094-098897"
}